// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:13be765e-5df2-41e7-9d08-74af6285980e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JQ6wC4CY3",
    "aws_user_pools_web_client_id": "6endda605j4pf10tnva3tg6vr2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wewo5p46djdyhi5uiyaqst4uue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "azopbucket20200206190858-worldev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
